apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application-from-will
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/FionaLeitz/iot_fleitz.git'
    tergetRevision: master
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true